### ISSUE TITLE
Too slow to start a basic server

### ISSUE THREAD

**Issue by chenyong** [coast-framework/coast#1]
I think I need something in Clojure to replace expressjs as my HTTP tool for serving files and JSON APIs, plus some other scripting works related. So... I want to use a server like a script.

Coast appear too slow for my case in startup. Any idea to make it starts up faster? I mean I may not need some of the features, like database, or templating. In expressjs, middleware are splitted into several modules, I can pick what I want before really using it. I suppose it would reduce the code size Coast loads during startup?

On my machine(2.3 GHz Intel Core i5):

```bash
=>> time clj -m app.main
Server is listening on port 3000
listening on 3000...

real	0m6.020s
user	0m15.017s
sys	0m0.507s
```

```clojure
(ns app.main
  (:require [coast.core :as coast]))

(defn home [request]
  (coast/ok "Hello World"))

(def app (-> (coast/get "/" home)
             (coast/match-routes)))

(defn -main []
  (coast/start-server app {:port 3000})
  (println "listening on 3000...")
  (System/exit 0))
```

**Comment by swlkr** [comment]
I just saw this. Yeah, I see what you're saying, coast is definitely slower to start and packed with a bunch of stuff that assumes server side rendering. I'm interested in how to make it more modular, but not really sure how to proceed without doing something like what [luminus](http://www.luminusweb.nets) does where all of the deps are sitting in the project.clj.

I purposely wrapped everything up into one dependency to make it easier, but it's definitely not easy to split apart haha.

**Comment by chenyong** [comment]
Another question is, which jars take the most time to load among...

```edn
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [potemkin "0.4.4"]
                 [http-kit "2.2.0"]
                 [trail "2.1.0"]
                 [trek "0.1.4"]
                 [bunyan "0.1.1"]
                 [environ "1.1.0"]
                 [hiccup "1.0.5"]
                 [ring/ring-core "1.6.2"]
                 [ring/ring-defaults "0.2.3"]
                 [ring/ring-devel "1.5.0"]
                 [org.postgresql/postgresql "42.1.4"]
                 [org.clojure/java.jdbc "0.7.1"]
                 [org.clojure/tools.namespace "0.2.11"]
                 [oksql "1.2.0"]
                 [inflections "0.13.0"]
                 [prone "1.1.4"]
                 [org.clojure/data.json "0.2.6"]])
```

**Comment by swlkr** [comment]
I just tried with the latest version, here are my results:

```clojure
(ns slow
  (:require [coast.core :as coast]))

(defn home [request]
  (coast/ok "Hello World"))

(def app (-> (coast/get "/" home)
             (coast/wrap-coast-defaults)))

(defn -main []
  (coast/start-server app {:port 3000})
  (System/exit 0))
```

```bash
$ time COAST_ENV=prod clj -m slow
Server is listening on port 3000

real	0m4.823s
user	0m16.103s
sys	0m0.452s
```

What's really interesting is that even without starting the server, just requiring coast takes > 4s on my machine

```clojure
(ns slow
  (:require [coast.core :as coast]))

(defn -main []
  (System/exit 0))
```

```bash
$ time COAST_ENV=prod clj -m slow

real	0m4.712s
user	0m16.742s
sys	0m0.479s
```

Removing the require line drops the time to ~ 1s

```clojure
(ns slow)

(defn -main []
  (System/exit 0))
```

```bash
$ time COAST_ENV=prod clj -m slow

real	0m1.219s
user	0m2.477s
sys	0m0.159s
```

**Comment by chenyong** [comment]
People always say: Clojure runs fast, but starts up slowly.

**Comment by swlkr** [comment]
FWIW I did manage to get the startup time down with the latest version on a new-ish 2016 15" MBP w/ touch bar to 3.2s. I'm curious about `Graal-VM`'s `native-image`, but unsure how to test it out 😅

Here's the code I used to test

```clojure
(ns server
  (:require [coast.delta :as coast]
            [coast.prod.server :as prod.server])
  (:gen-class))

(def routes [[:get "/hello/:name" `hello]])

(defn hello [req]
  (str "hello " (-> req :params :name)))

(def app (coast/app routes))

(defn -main [& args]
  (prod.server/start app)
  (System/exit 0))
```

```sh
$ time clj -m server

real	0m3.207s
user	0m11.025s
sys	0m0.355s
```

**Comment by dawran6** [comment]
> People always say: Clojure runs fast, but starts up slowly.

@chenyong I think you're right about Clojure's startup time. However, this is rarely an issue if you take advantage of Clojure's REPL and interactive development flow - where we build our program incrementally inside the REPL without ever quitting.

Feel free to check out my ["Web development with Coast and Clojure" series](https://www.youtube.com/playlist?list=PLb5SjnGEsSJcrRN6HtAtbOJpPZWhbqzpI). You can see this in the series that I only exit my program when I include a new dependency in the project. Other times, I re-evaluate forms and re-bind vars to get immediate feedback.

Another comment is that this isn't an issue specifically to Coast or Clojure. The origin is because Java/JVM is mostly optimized for throughput not startup time. Hypothetically, if you find a way to run the program on another host platform (say node) you'll probably gain a lot of startup speed.

**Comment by jiyinyiyong** [comment]
Thanks for replying. I will stick to Node.js . Not a serious project but I got my own scripts https://github.com/mvc-works/skir .
