### ISSUE TITLE
SQLite3 rollback of add-column breaks.

### ISSUE THREAD

**Issue by armstnp** [coast-framework/coast#107]
Migration:
```clojure
;; ...
(add-column :item :sell-price :integer)
;; ...
```

Rollback command and output
```
> coast db rollback
[...]
-- Rolling back: 20221013205645_add_prices_to_item ---------------------

alter table item drop column sell_price

-- 20221013205645_add_prices_to_item ---------------------

Exception in thread "main" java.sql.BatchUpdateException: batch entry 0: [SQLITE_ERROR] SQL error or missing database (near "drop": syntax error)
[... Stack trace ...]
```

SQLite3 now [supports the dropping of columns](https://www.sqlite.org/lang_altertable.html#alter_table_drop_column), but it seems the driver in use by Coast preemptively refuses.

Given faulty migrations can lock down the entire development process, it would be helpful to either supply a SQLite-specific means to handling this (perhaps a gen-sym'd table to create, copy to, and rename once the original is destroyed, as is the common technique), or advising to perform SQLite column migrations in a SQL file instead of a Clojure one.

**Comment by swlkr** [comment]
Oh you know what, this might be the version of https://github.com/xerial/sqlite-jdbc used in https://github.com/coast-framework/template 

I'm going to bump it in that repo

**Comment by armstnp** [comment]
Good call! Will close this since it's not integral to the framework itself.
