### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [coast-framework/coast#13]
Hello! @swlkr 

I contribute to open source software by designing logos. And i designed a logo for it. 

i combined coast and clojure and I made it compatible. I used Clojure colors. There are 4 different variations. If you like it, I'll send a pr for one of these and update the readme file.  I will wait for feedback. 

Have a nice day!

![coast](https://user-images.githubusercontent.com/36298335/42369067-7c80f996-8111-11e8-83c5-d2f1ee2ebac1.jpg)

**Comment by swlkr** [comment]
I like the first one, is there any way it can be svg or something? I wanted to use it on the website I’m making for it too.

**Comment by reallinfo** [comment]
Sure,
I created a folder named logo and I have added all the required files into it. Also, I updated the readme file. Any problems?

https://github.com/coast-framework/coast/pull/14
