### ISSUE TITLE
`make repl` fails

### ISSUE THREAD

**Issue by px0** [coast-framework/coast#19]
`make repl` fails with the attached error message.

It seems to work if I change the Makefile from 
```
repl:
        clj -R:nrepl bin/repl.clj
```
to
```repl:
        clj -R:repl bin/repl.clj
```
(repl instead of **n**repl)

```
/tmp/myapp❯  make repl                                                                                
clj -R:nrepl bin/repl.clj
Error building classpath. Specified aliases are undeclared: [:nrepl]
make: *** [repl] Error 1
```

**Comment by swlkr** [comment]
Thanks for letting me know, I’ll fix this today!

**Comment by swlkr** [comment]
This has been fixed here https://github.com/coast-framework/template/commit/6895b584940da616fb9a6b0aa62e43964b4e47b1

among other things, like `make test`
