### ISSUE TITLE
Update model/controller generator templates to make use of database EDN queries

### ISSUE THREAD

**Issue by mgerlach-klick** [coast-framework/coast#24]
Many of the generator templates seem out of date now that the EDN queries are introduced.

**Comment by swlkr** [comment]
Ha, yeah they are, I’ve really got to bring them up to speed, it would be nice to have a generator for edn schema stuff as well, although that’s not a lot of typing already

**Comment by mgerlach-klick** [comment]
Hey, just so I know, is it useful if I pepper you with issues or is that just annoying? I really like your framework and want it to get to a state where I can use it :)
Also, I'm the same as the other guy (px0), I'm just bad at switching between my personal and work accounts.

**Comment by swlkr** [comment]
haha, yeah bring on the issues!

**Comment by mgerlach-klick** [comment]
I love it!!!

**Comment by swlkr** [comment]
Talked about this in #20 🙌
