### ISSUE TITLE
url-for needs unqualified keys?

### ISSUE THREAD

**Issue by mgerlach-klick** [coast-framework/coast#29]
Hey, what do you think of this:
Through EDN queries, all the results come back with qualified namespaces, for instance here's what i'm working on right now:
`(q '[:pull [:brand/id :brand/url :brand/company :brand/last-visited :brand/name]])`
now I want to `url-for` those brands, but currently I have to do this:
`[:a {:href (url-for :view-brand {:id (:brand/id row)})}]`

What if `url-for`, if it doesn't find the key it is looking for, automatically disqualifies the keys and looks there? This would allow a simple:
`[:a {:href (url-for :view-brand row)}]`

Cf. https://github.com/cjsauer/disqualified

**Comment by swlkr** [comment]
Oh wow yeah, that's really useful! Definitely going to unqualify those keywords very soon.

**Comment by mgerlach-klick** [comment]
Or maybe turn it into :namespace_name and then i make the route go to `:get "/view-brand/:brand_id" :brand.read/view :view-brand]` or something to prevent conflicts. Just thinking out loud..
