### ISSUE TITLE
Add a small sample project

### ISSUE THREAD

**Issue by mgerlach-klick** [coast-framework/coast#31]
If you have a few minutes, could you add a small sample project? Maybe the ubiquitous blog or todo app? The documentation is all over the place and I mostly resort to reading the source and trial & error to figure out how things work in the current version. This could also be a first step towards some tests as mentioned in https://github.com/coast-framework/coast/commit/919b5db1e49a91d5cf38be123ab9e2b18619b660#commitcomment-30666404

**Comment by ferrucc-io** [comment]
I might make a test project with a blog post

**Comment by swlkr** [comment]
@ferrucc-io and I open sourced https://github.com/magehash/magehash as a more complex example app, but it does show how far you can go with coast as it is now.

**Comment by swlkr** [comment]
I also made another, much smaller app: https://github.com/swlkr/photoparty

It doesn't have auth and it only has one table in the db, so it should be pretty straightforward

**Comment by swlkr** [comment]
I've made a docs website which does show off everything except db integration:

https://github.com/coast-framework/docs

Still working on that screencast though
