### ISSUE TITLE
edn migration: how to change column?

### ISSUE THREAD

**Issue by mgerlach-klick** [coast-framework/coast#32]
I realized that one of my columns shouldn't be an `ident` and should be nillable. So I decided to create a new migration that changed this:
`[ {:db/col :user/image-url
  :db/type "text"
  :db/nil? true}]`

This didn't work:
> Exception in thread "main" org.postgresql.util.PSQLException: ERROR: column "image_url" of relation "user" already exists

So, what's the right way to migrate a schema?

**Comment by swlkr** [comment]
Oh that's interesting, having future migrations overwrite old ones. I didn't think about that, what I do is rollback first then change the existing schema, but that only works if you haven't already migrated in prod.

There is no way to do this currently 😬

What you did should work though, it should know that the old column was an ident, and the new column isn't and generate this:

```sql
alter table user drop constraint user_image_url_key
```

As for the rest of the changes you could make to columns… well that's something else entirely. It'll need to know when a datatype is changing in `:db/type` and set the new type as long as the data still works in that column, same thing with `not null`… the list goes on.

**Comment by mgerlach-klick** [comment]
Yeah, I ended up doing it manually, but I find this is something I do fairly often during development. 
Is there a way to allow for sql migrations, which would allow that, and then regenerating schema.edn from the database schema somehow?

**Comment by swlkr** [comment]
That could work, coast could look at the current schema after a sql migration and update schema.edn accordingly. It would be really nice to infer `schema.edn` from the database schema, that way you could use sql migrations only and still be able to use pull.

**Comment by swlkr** [comment]
#48

**Comment by swlkr** [comment]
Again, those edn migrations were a pain, so I've added `rename-column` in the latest version which does do this

http://coastonclojure.com/docs/migrations.md#user-content-schema-table-api
