### ISSUE TITLE
errors are rendered as one big blob

### ISSUE THREAD

**Issue by mgerlach-klick** [coast-framework/coast#33]
This is likely due to the hiccup-escape feature. You have to tell hiccup that this time HTML is okay :)

![2018-09-26 at 8 43 pm](https://user-images.githubusercontent.com/4621981/46117008-e8525880-c1cc-11e8-8f5e-d974e2c77f7c.png)

**Comment by swlkr** [comment]
Yeah that's true, it works great though, super excited that XSS is off by default

**Comment by swlkr** [comment]
Making those `<br/>s` show again https://github.com/coast-framework/coast/commit/c8773acfb3cbded4e16e1ba6e745542f9e685cfc

**Comment by mgerlach-klick** [comment]
>  super excited that XSS is off by default

I'm not. I can't inject `[:script]`s into my views anymore! :(

**Comment by mgerlach-klick** [comment]
Not even the layout!

**Comment by mgerlach-klick** [comment]
I take it back, I noticed i can use `coast/raw` to inject unescaped strings!
