### ISSUE TITLE
Primary key schema is problematic

### ISSUE THREAD

**Issue by mgerlach-klick** [coast-framework/coast#37]
Currently, primary keys get generated as `integer nextval('table_id_seq'::regclass)`. This is problematic when deleting the last entry in a table, because then postgres will try to assign the previously used id, and will error out because this id, though deleted, is still in use.

I think there is a better way to get the next primary key in postgres, but I'm on the run and can't look it up right now

**Comment by swlkr** [comment]
Hm, interesting, I did not know this. I shamelessly borrowed this from rails migrations but yeah if there's a better way, let's do that

**Comment by mgerlach-klick** [comment]
I read up on it, and `serial` is the right way (it was just displayed funny in DataGrip). There is an issue though.. I'll investigate and get back to you

**Comment by swlkr** [comment]
#48

**Comment by swlkr** [comment]
I’m going to close this for now
