### ISSUE TITLE
404 on every root when first starting Coast

### ISSUE THREAD

**Issue by ferrucc-io** [coast-framework/coast#39]
I'm running Clojure 1.9.0 on my macOS machine running High Sierra, and whenever I start a coast app I get a 404 Error on every route until I change a line of code inside of the route and save it.

I can even delete the changes I make and save them and the route keeps working. It seems like the routes in dev environment are "rendered" only when "hot-reloaded", the rest of the time they trigger a "GET / :home.index/view 404 text/html; charset=utf-8 5ms"

I tried this on the MH codebase and also on some hobby projects I setup and the problem persists!

Will try and look into the codebase and figure out what's going on, as I don't know if this issue is repeatable on other devices

**Comment by ferrucc-io** [comment]
I'm starting coast by 'make server' and the project was automatically generated

**Comment by swlkr** [comment]
Ahhhh that’s it. I should make this work though, my intention was that everything in dev starts from the repl, like you start the repl, load every namespace in every file, then run (server/-main) to start the server.

I’ll bump the minor version tonight to eta-1.0.4 to handle make server and make sure the routes get loaded
