### ISSUE TITLE
Allow a whole database backed application to be run from one clojure file

### ISSUE THREAD

**Issue by swlkr** [coast-framework/coast#40]
This is related to #32 and #26 but it's a little bigger in scope, I'd like to change coast so that everything can be run from one file, instead of *requiring* multiple files just to read/write to a database, this is what I'm working on currently:

```clojure
(ns server
  (:require [coast]))

(def add-todos [{:db/col :user/name :db/type "text" :db/case-sensitive? false :db/unique? true :db/nil? false :db/default “‘’”}
                {:db/rel :user/todos :db/type :many :db/ref :todo/user}
                {:db/rel :todo/user :db/type :one :db/ref :user/id}
                {:db/col :todo/name :db/type "text"}
                {:db/col :todo/done :db/type "boolean" :db/default false :db/nil? false}])

(def routes [[:get "/" ::home]])

(defn home [req]
  (coast/ok
   (coast/q '[:pull [user/name
                     {:user/todos [todo/name todo/done]}]])))

(def app (coast/app {:routes/api routes}))

(defn -main [& [port]]
  (coast/migrate add-todos)
  (coast/server app {:port port}))

```

It was inspired by this reddit thread here https://www.reddit.com/r/Clojure/comments/9mjuon/new_clojurians_ask_anything/e7fnjhu/

I didn't have a good response that I could put in one reddit comment, I didn't want to say, generate this whole thing with all of these files, coast is supposed to be easy, the easiest thing you could do is this:

```bash
mkdir -p todos todos/src
cd todos
touch deps.edn todos/src/server.clj
echo '{:paths ["src"] :deps {org.clojure/clojure {:mvn/version "1.9.0"} coast-framework/coast.theta {:mvn/version "1.0.0"}}}' >> deps.edn
```

and then copy and paste the above and you're off and running with `clj -m server`.

No repls, no extra files, no migration files, no postgres servers.

I'm hoping it's the easiest way to start a database backed web application in any language.

**Comment by mgerlach-klick** [comment]
Looks sweet! I'd love to have the DB querying separated from the migration stuff! That way I can 1) use sql migrations, which i still like better and 2) graft it onto an existing project 

I don't mind maintaining the schema separately from the table. I've tried that in one project with walkable and it was just fine. Kinda nice, in fact, to have it all laid out at all times.

**Comment by swlkr** [comment]
Ohhh, it wasn’t clear from the example, I used this as a placeholder, but yeah the schema that you pass in is a real db schema that gets translated to sql and does alter table and all of those things. The goal is if you change the schema by removing one or more of those elements from the vector, the database will change by dropping columns, or if you change a type of a column it will change the column in the database too. 

Also I’m trying to add support for sqlite and I’m trying to move the schema.edn file to the db, but I mean if there’s value in having a more human readable schema file like walkable, that could be something too

**Comment by mgerlach-klick** [comment]
Oh, I read this as 'the database is already defined, i'm just giving you the EDN schema here to work with it'.

Personally I'd very much prefer giving the query/transact functions a schema to work with, rather than having migration magic happening that I can't control. Would it be an option to give your functions a second arity with the schema, and if it's there it uses that, and if not, then it refers to the schema.edn that your migrations have created?

**Comment by swlkr** [comment]
Yeah, hit me up on either telegram or twitter DMs I'm swlkr on both
