### ISSUE TITLE
Support more #inst in where, string where clauses

### ISSUE THREAD

**Issue by mgerlach-klick** [coast-framework/coast#42]
`(coast/q [:pull [:visit/id :visit/visit] :where [:visit/visit #inst "2018-09-27"]])` fails with 

>PSQLException Can't infer the SQL type to use for an instance of java.util.Date. Use setObject() with an explicit Types value to specify the type to use.  org.postgresql.jdbc.PgPreparedStatement.setObject (PgPreparedStatement.java:967)

Also, how about supporting pure strings in the where clauses? Something like:
` (coast/q [:pull [:visit/id :visit/visit] :where ["visit.visit > '2018-09-27'::date"]])`

Of course, this would either require putting the where clauses in vectors:
```clj
(coast/q [:pull [:visit/id :visit/visit :visit/person] 
:where [
["visit.visit > '2018-09-27'::date"]
[:visit/person "Max"]])
```

or a sentinel value:
```clj
(coast/q [:pull [:visit/id :visit/visit :visit/person] 
:where [
:coast/sql-string "visit.visit > '2018-09-27'::date"
:visit/person "Max"
]])
```

**Comment by swlkr** [comment]
The latest version of coast (theta) does support strings in where clauses: http://coastonclojure.com/docs/queries.md#user-content-where-clauses
