### ISSUE TITLE
Help wanted: DB creation issue

### ISSUE THREAD

**Issue by rlhk** [coast-framework/coast#45]
Got a postgresql server running in Mac docker with user name & password. Good to connect with psql cli.

But always get the error
`Exception in thread "main" org.postgresql.util.PSQLException: The server requested password-based authentication, but no
password was provided.`

Tried modified the .env file but no luck. Is there a sample that works with authentication ?

**Comment by swlkr** [comment]
Hm, this is a good question, let me test it out and see what it would take to get this working

**Comment by swlkr** [comment]
So here's what I did to reproduce this. I changed my `pg_hba.conf` to look like this:

```sh
# TYPE  DATABASE        USER            ADDRESS                 METHOD
 
# "local" is for Unix domain socket connections only
local   all             all                                     password
# IPv4 local connections:
host    all             all             127.0.0.1/32            password
```

Then I ran the following in the db

```sql
create database pw_test_dev;
create user pw_test_dev with password 'password';
```

Then, I changed my `.env` file `DATABASE_URL` property from this:

```sh
DATABASE_URL=postgres://localhost:5432/pw_test_dev
```

to this:

```sh
DATABASE_URL=postgres://pw_test_dev:password@localhost:5432/pw_test_dev
```

When I started the repl and connected to the db, it worked!

**Comment by rlhk** [comment]
Cool. Will try again.
