### ISSUE TITLE
many-to-many relation in edn migration

### ISSUE THREAD

**Issue by mgerlach-klick** [coast-framework/coast#46]
I can't figure out how to do a many-to-many relation in edn migrations.
Say i have links and users, and a user can upvote N links, and a link can have N users upvoting it.. how would I express that?

**Comment by swlkr** [comment]
Just wanted to put this here #48

**Comment by swlkr** [comment]
I kind of moved away from the confusing edn migrations, but this is supported in the latest version here:

http://coastonclojure.com/docs/relationships.md#user-content-has-many-through
