### ISSUE TITLE
Easier migrations

### ISSUE THREAD

**Issue by swlkr** [coast-framework/coast#48]
Here's what this will look like, when you run either `coast gen migration` from the terminal or `(coast/gen :migration)` from the repl, a new migration file will be created in the `db/migrations` folder with a timestamp and a `.clj` extension, similar to the edn and sql migrations.

Here's what a potential `clj` migration might look like:

```clojure
; resources/migrations/20181222100534-create-customer-table.clj
(create-table :customer
   (text :first-name {:null? false})
   (text :email {:collate "nocase"}))
```

or if you want to add a column after the fact

```clojure
(add-column :customer :last-name :text)
```

or if you want to drop a column

```clojure
(drop-column :customer :last-name)
```

**Comment by mgerlach-klick** [comment]
Looks great, but I'm unclear on whether these migrations will lead to `q` queries still working?

**Comment by swlkr** [comment]
So yeah, they're just thin clojure wrappers over SQL DDT syntax, but yes, it's going to look at the foreign keys and generate the coast schema from the database like you were talking about before, and then if you want to customize it, you can. So here's an example using that doc:

```clojure
(create-table :customer
  (text :email :null false :unique true :case-sensitive true)
  (text :password :null false)
  (timestamps))

(create-table :todo
  (text :name :null false)
  (timestamp :finished-at :null false)
  (references :customer)
  (timestamps))
```

This gets migrated with `make db/migrate`, coast will then reads the db schema that results from this with a functions named `coast-schema` and `gen-schema` or something and will create the `coast-schema` table and puts in a bunch of edn in it (which is what currently happens in the latest branch):

```clojure
; coast-schema table
{:customer/email #:db{:type "text" :null false :unique true :case-sensitive true}
 :customer/password #:db{:type "text" :null false}
 :customer [:customer/id :customer/email :customer/password :customer/created-at :customer/udpated-at]
 :todo/name #:{:type "text" :null false}
 :todo/finished-at #:{:type "timestamp" :null false}
 :todo/customer #:db{:type :one :ref :customer/id}
 :todo [:todo/id :todo/name :todo/finished-at :todo/created-at :todo/updated-at]
 :customer/todos #:db{:type :many :ref :todo/customer}} ; this is inferred from foreign keys and pluralization
```

It attempts to figure out the `customer/todos` pull name based on pluralizing the table where the foreign key is. Customization will happen in the `resources/schema.edn` file, you will be able to overwrite pull names in case it doesn't make any sense `customer/persons` comes to mind as making no sense, and I guess you can write out the whole file for an existing schema. There will also be another arity for `q` which takes a schema since I know you weren't cool with all of coast's magic

**Comment by swlkr** [comment]
I've come up with something a little more readable for the pull queries, instead of storing all of the schema info in `resources/schema.edn` coast can just store the `one-to-many`, `many-to-one` and `many-to-many` relationships as keys in a map like this. Let's say you have three tables:

```sql
create table creator (
  id integer primary key
)

create table subscriber (
  id integer primary key,
  email text not null
)

create table subscription (
  id integer primary key,
  creator_id integer, --no references so no foreign key and it has a trailing _id
  subscriber_id integer --no references so no foreign key also has trailing _id
)
```

And you want to pull data out of your database like this:

```clojure
(pull [:creator/id
       {:creator/subscriptions [subscription/id
                                {:subscription/subscriber [subscriber/email]}]}]
      [:creator/id 1])
```

You'd write out your `resources/schema.edn` file like this:

```clojure
{:subscription/creator [:one :creator/id :subscription/creator-id]
 :subscription/subscriber [:one :subscription/subscriber-id :subscriber/id]
 :creator/subscriptions [:many :subscription/creator]
 :subscriber/subscriptions [:many :subscription/subscriber]}
```

This way it's easier to write manually in the case of no foreign keys and it gives the framework only the data needed to do the pull joins. I'm still working on a way to make a "shortcut" through the join table, I'm thinking something like this:

```clojure
{; … that other stuff from before
 :creator/subscribers [:many :creator/subscriptions :subscription/subscriber]}
```

So then you can query like so:

```clojure
(pull [{:creator/subscribers [:subscriber/email]}]
```

Normally you could avoid most of this by specifying foreign keys with no trailing `_id` in the column name like this:

```sql
create table creator (
  id integer primary key
)

create table subscriber (
  id integer primary key,
  email text not null
)

create table subscription (
  id integer primary key,
  creator integer references creator(id),
  subscriber integer references subscriber(id)
)
```

and just having this in your `schema.edn`

```clojure
{:subscription/creator :one
 :subscription/subscriber :one
 :creator/subscriptions :many
 :subscriber/subscriptions :many}
```

**Comment by swlkr** [comment]
Closed by https://github.com/coast-framework/coast/releases/tag/coast.theta-1.0.0
