### ISSUE TITLE
How to set session duration?

### ISSUE THREAD

**Issue by iamboony** [coast-framework/coast#52]
How would one go about changing the duration of the session to, for example, indefinite?

**Comment by swlkr** [comment]
coast uses ring's [cookie session store](https://github.com/ring-clojure/ring/wiki/Sessions#session-stores) by default, so you can control it like you would with ring's wrap-session:

```clojure
(def app (coast/app {:routes routes/routes
                     :session {:cookie-attrs {:max-age 3600}}}))
```

**Comment by swlkr** [comment]
It's worth pointing out that you can pass any ring defaults through that second arg in map https://github.com/ring-clojure/ring-defaults#customizing

**Comment by iamboony** [comment]
I'm going to try it out, thanks! Currently I resorted to

```
(ns middleware
  (:require [coast :refer [redirect]]
            [ring.middleware.session :refer [wrap-session]]))

(defn wrap-infinite-cookie [handler]
  (fn [request]
    (wrap-session handler {:cookie-attrs {:max-age 31556926}})
    (handler request)))
```

Which I think also works. Session has not been destroyed so far at least (approximately 24h).
