### ISSUE TITLE
How to add cookies instead of sessions?

### ISSUE THREAD

**Issue by askosh** [coast-framework/coast#53]
I've come across a thing where if using sessions with Coast on Heroku, the session gets destroyed every now and then and so logs all the users out at random. So I'm wondering how to use cookies instead of sessions, to create persistent sessions for apps that have their memory cleaned at random like Heroku apps?

**Comment by swlkr** [comment]
Coast uses the [ring cookie store](https://github.com/ring-clojure/ring/wiki/Sessions#session-stores), which stores the session in an encrypted cookie, so it should be able to handle heroku's restarts.

You have to set the `SECRET` environment variable for the cookie store to work, if it isn't set every time the app restarts it will reset everyone's session.

You should be able to use a [jdbc store](https://github.com/luminus-framework/jdbc-ring-session) or a [redis store](https://github.com/paraseba/rrss) though, pass this to coast's `app` function:


```clojure
(def store (jdbc-store {}))

(def app (coast/app {:routes routes/routes
                     :session {:store store}}))
```

**Comment by askosh** [comment]
Ah, didn't know about the `SECRET` env. This more than answers my question tho', thank you yet again!
