### ISSUE TITLE
make db/create needs readline version 7.0.1

### ISSUE THREAD

**Issue by natetech333** [coast-framework/coast#54]
First, let me say... this is an incredible framework. I've been looking for months. For a framework for Clojure. This is pulling me more into the Clojure community, coming from Rails.

Run command...
make db/create

It appears that the lib path is hardcoded to readline version 7

I used brew to switch to version 7

```brew switch readline 7.0.1```

nathans-MacBook:mycoastapp nathansire$ make db/create
clj -A\:db/create
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
  Referenced from: /usr/local/bin/rlwrap
  Reason: image not found
/usr/local/bin/clj: line 7: 32949 Trace/BPT trap: 5       rlwrap -r -q '\"' -b "(){}[],^%3@\";:'" clojure "$@"
make: *** [db/create] Error 133

**Comment by swlkr** [comment]
Hm this is interesting, I honestly didn't know what version of readline it was using.

I'm actually not sure how to fix this, or even if I can? is this related to the version of clojure?

I've installed clojure through homebrew, maybe that's why I haven't run into this problem

**Comment by swlkr** [comment]
I'm on clojure cli version 1.10.0.414 (from `brew install clojure`)

**Comment by natetech333** [comment]
clojure 1.9.0.273
I also used brew on osx el capitan, to install clojure

**Comment by natetech333** [comment]
My first guess... somewhere in the code... maybe not your code, other code... it has harded a dependency to readline version 7. I will search the code and try to find it.

**Comment by swlkr** [comment]
I’m going to close this for now
