### ISSUE TITLE
How do I add an exception for a POST route to not care for CSRF?

### ISSUE THREAD

**Issue by askosh** [coast-framework/coast#57]
I want to set up some POST webhooks that target my Clojure app that runs on Coast, but since it will not be having the CSRF token in its request payload, it will not even get to it's function and will be unauthorized before that, rendering the webhook useless. 

Is there a way to circumvent that?

**Comment by askosh** [comment]
Nevermind, realized that API routes is what I'm looking for. Closing this.

**Comment by swlkr** [comment]
I should probably highlight this more in the docs.

You shouldn’t have to split up your routes into api/non-api, you should be able to return any format from any route or multiple formats based on content-type.

Im working on an update where youshould also be able to turn off CSRF from any group of routes, like this:

```clojure
(coast/site {:anti-forgery false}
  [:get “/“ :home/index])
```
