### ISSUE TITLE
Coast not allowing :options route?

### ISSUE THREAD

**Issue by askosh** [coast-framework/coast#59]
When writing an API in Clojure using Coast that a modern SPA would communicate with, since `application/json` content type preflights a OPTIONS request to check for CORS before landing on the actual route, in order to make an API with it, I'd need an ability to catch OPTIONS requests. Any suggetions?

**Comment by swlkr** [comment]
Luckily, coast can use any old ring middleware, so this should work:

```clojure
(ns server
  (:require [coast]
            [routes]
            [ring.middleware.cors :as cors])
  (:gen-class))

(def app (-> (coast/app {:routes routes/routes})
             (cors/wrap-cors :access-control-allow-origin [#".*"]
                             :access-control-allow-methods [:get :put :post :delete])))

(defn -main [& [port]]
  (coast/server app {:port port}))

(comment
  (-main))
```

[ring.middleware.cors is here](https://clojars.org/ring-cors)

You can add it to your `deps.edn`:

```clojure
{:paths ["resources" "src"]

 :deps
 {org.clojure/clojure {:mvn/version "1.10.0"}
  coast-framework/coast.theta {:mvn/version "1.4.1"}
  org.xerial/sqlite-jdbc {:mvn/version "3.25.2"}
  ring-cors {:mvn/version "0.1.13"}}}
```

**Comment by askosh** [comment]
Perfect, this solves it marvellously. Thank you again!
