### ISSUE TITLE
[[: not found and misleading success message

### ISSUE THREAD

**Issue by ejelome** [coast-framework/coast#71]
Hi, thanks for Coast, it's really an interesting project.

I'm a first time user of Coast so I could have wrong setup before getting these problems:

```
$ coast new zero
/usr/local/bin/coast: 7: /usr/local/bin/coast: [[: not found
/usr/local/bin/coast: 17: /usr/local/bin/coast: [[: not found
/usr/local/bin/coast: 7: /usr/local/bin/coast: [[: not found
/usr/local/bin/coast: 27: /usr/local/bin/coast: [[: not found
Downloading a fresh copy of coast...
mkdir: cannot create directory ‘zero’: File exists
Created a new coast project in directory zero
```

**Comment by swlkr** [comment]
I tried this in ubuntu and sure enough, yep it throws that error, I got rid of the double square braces and it appears to at least not throw that error now, so re-download the coast script from master and let me know how it goes.

[Here's the commit that fixed this](https://github.com/coast-framework/coast/commit/a93f94271e41db9a6f1c5572645d3e06498a860e)

**Comment by ejelome** [comment]
Looks great! Working as expected, although the success message is still misleading (it could be or not really that important though):

```
$ mkdir zero
$ coast new zero
Downloading a fresh copy of coast...
mkdir: cannot create directory ‘zero’: File exists
Created a new coast project in directory zero
```

I'll close this cause the main trouble is fixed, thanks! :)
