### ISSUE TITLE
Can't deploy to Heroku

### ISSUE THREAD

**Issue by askosh** [coast-framework/coast#75]
Heroku seems to want a project.clj file, which does not come with Coast:

```
App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/clojure.tgz
remote:        Could not find a 'project.clj' file! Please ensure it exists and is checked into Git.
```

**Comment by swlkr** [comment]
Hm yeah I kind of left heroku in the dust when I switched over to tools.deps

I found this though which may help

https://www.gertgoet.com/2019/02/06/deploying-a-tools-deps-clojure-project-to-heroku.html

**Comment by askosh** [comment]
It did! Thank you :)
