### ISSUE TITLE
git vs https in deps.edn

### ISSUE THREAD

**Issue by michaelteter** [coast-framework/coast#76]
Is there a reason why the generated deps.edn uses "git@github.com:" instead of "https://github.com/" for the cognitect test-runner?  Further down in deps, https is used for juxt pack.alpha.

Using git instead of https fails in Cursive for me, probably because I haven't figured out how to properly configure the IDE for my custom ssh (different githubs for different users/keys).  Changing to https for test-runner clone works fine and avoids this problem.

**Comment by swlkr** [comment]
there’s no reason really, i’ll change everything to https
