### ISSUE TITLE
`make uberjar` failed: "java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter"

### ISSUE THREAD

**Issue by dawran6** [coast-framework/coast#81]
This issue is related to "[Java 9/10 `javax.xml.bind.DatatypeConverter` issue #25](https://github.com/juxt/pack.alpha/issues/25)", which was fixed since `0878b52b7718e4b348a500dce0b3edc5b555a4f1`.

The latest stable version is `2769a6224bfb938e777906ea311b3daf7d2220f5` according to the README. I can submit a PR to the `coast-framework/template` repo once I test it on my machine.

The Java version on my machine is:

```
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode)
```

**Comment by swlkr** [comment]
Yeah, PR away!
