### ISSUE TITLE
Missing doctype in the wrap-layout middleware

### ISSUE THREAD

**Issue by dawran6** [coast-framework/coast#86]
It sounds important to include the `doctype` in the html:

> In HTML, the doctype is the required "<!DOCTYPE html>" preamble found at the top of all documents. Its sole purpose is to prevent a browser from switching into so-called “quirks mode” when rendering a document; that is, the "<!DOCTYPE html>" doctype ensures that the browser makes a best-effort attempt at following the relevant specifications, rather than using a different rendering mode that is incompatible with some specifications.

~ from [MDS web docs](https://developer.mozilla.org/en-US/docs/Glossary/Doctype)

The minimum example to demonstrate the issue is:

```clojure
(def app
  (coast/app
    {:routes
      (coast/routes
        (coast/site
          (coast/with-layout (fn [req body] [:html [:body body]]) [:get "/" ::index])))}))

(defn index [req] [:h2 "Home"])

(coast/server app {:port 1338})

;; Go to localhost:1338 and the html doesn't have the "<!DOCTYPE html>" at the beginning.
```

My current solution is to include the doctype explicitly it in the layout component:

```clojure
(require '[hiccup.page])

(defn layout [request body]
  (list                           ;; <- need this to return the extra doctype
    (hiccup.page/doctype :html5)  ;; <- doctype here
    [:html
     [:head
      [:meta {:name "viewport" :content "width=device-width, initial-scale=1"}]
      (coast/css "bundle.css")
      (coast/js "bundle.js")
      [:body
       body]]]))
```

I think it aligns with the philosophy of Coast to handle this in the framework.
We should be able to do this in the `coast.middleware/wrap-layout`.

**Comment by swlkr** [comment]
Yeah I kind of did exactly this in the next branch:

I made it a little nicer by putting it in the coast namespace but yeah, it could probably happen by default:

https://github.com/coast-framework/template/blob/next/src/layouts.clj#L9

**Comment by dawran6** [comment]
Oh cool! Can't wait for the next release! Thanks for responding :)
