### ISSUE TITLE
Update routes file when coast gen route is called

### ISSUE THREAD

**Issue by swlkr** [coast-framework/coast#89]
Right now you have to manually update the `routes.clj` file, that stinks.

Ideally, coast would just insert the new default routes when `coast gen route todo` is run.

```diff
(ns routes
  (:require [coast :refer [routes middleware]
            [routes.home :as home]
+           [routes.todo :as todo]))

(def home-routes
  (routes
    [:get "/" home/index]))

+(def todo-routes
+  (routes
+    [:get "/todo" index]
+    [:get "/todo/build" build]
+    [:post "/todo" create]

+   (middleware todo/set-todo
+      [:get "/todo/:id" show]
+      [:get "/todo/:id/edit" edit]
+      [:patch "/todo/:id" patch]
+      [:delete "/todo/:id" delete])))

(def app
  (routes
    home-routes
+   todo-routes))
```

Kind of related to #87 but much smaller in scope

**Comment by swlkr** [comment]
This is pretty much the main blocker before next is merged into master and then from there I'll work on updating the docs

**Comment by dawran6** [comment]
I'm more inclined to adding the `routes.todo` inside `todo-routes`:

```clojure
(ns routes.todo
  (:require [coast :refer [routes]))

(def todo-routes
  (routes
    [:get "/todo" index]
    [:get "/todo/build" build]
    [:post "/todo" create]

   (middleware todo/set-todo
      [:get "/todo/:id" show]
      [:get "/todo/:id/edit" edit]
      [:patch "/todo/:id" patch]
      [:delete "/todo/:id" delete])))
```

And add the `todo-routes` into the `app` manually:

```clojure
(ns routes
  (:require [coast :refer [routes middleware]
            [routes.home :as home]
            [routes.todo :refer [todo-routes]]))

(def app
  (routes
    home-routes
    todo-routes))
```

The reason is that I don't always need to include the whote routes into the app. Also, this seems a lot easier to implement 😛

**Comment by swlkr** [comment]
It's funny you mention that, because that's what the next branch does now, in that case, I'll leave it and I mean if you want all of the routes in one file, you can put them there, it just won't happen by default

**Comment by dawran6** [comment]
🙌 🙌 🙌
