### ISSUE TITLE
No such var: coast/no-content

### ISSUE THREAD

**Issue by aristotelesbr** [coast-framework/coast#99]
Hello. I'm trying to respond to a [request](https://coast.swlkr.com/docs/response#user-content-making-responses) using the function [`(cast/no-content)`](https://github.com/coast-framework/coast/blob/f31c74c7a875207a717a407e52c6449a53da2c69/src/coast/responses.clj#L41) but, it doesn't work like `(coast/ok {})` or `(coast/bad-request {})` or `(coast/not-found {})` 

When I try to compile I get an error:

```bash
 Syntax error compiling at (invoices.clj:35:3).
; No such var: coast/no-content
```

My editor doesn't seem to find the no-content function

<img width="779" alt="Screen Shot 2022-01-20 at 13 49 53" src="https://user-images.githubusercontent.com/8474381/150384196-3bbfc5eb-aee2-49b8-8f18-daf047f60189.png">

My editor also doesn't show some functions like `coast/created`

Is there something I'm not understanding?

**Comment by swlkr** [comment]
That's interesting, especially since they're all defined in the same place too, not quite sure why it's not working though, but a few of them are...

**Comment by vijaykiran** [comment]
@aristotelesbr  Which editor are you using? Can you give more info about your setup ? (lsp/nrepl etc.? )

**Comment by swlkr** [comment]
This looks like vscode, calva is the dominant clojure extension there, have yet to try to replicate this though

**Comment by aristotelesbr** [comment]
> Which editor are you using? Can you give more info about your setup ? (lsp/nrepl etc.? )

Sorry delay. I'm use vsCode with default LSP plugins(calva, etc). I don't know specifically details from LSP. I didn’t give segments to the studies with coast/clojure.🙁

**Comment by nathanielknight** [comment]
It looks like the function is defined, but not imported into `coast.clj` with the rest of them: https://github.com/coast-framework/coast/blob/master/src/coast.clj#L17-L25

If that's the problem, I'd be happy to submit a PR if that would be helpful.

**Comment by swlkr** [comment]
Ah, that's what it is, your PR is welcome!
